/**
 * Applies pending SQL migrations from `./drizzle` at startup (generated by `pnpm db:generate`)
 * and verifies the schema they create: an empty database must stop the process instead of
 * letting every request fail with `42P01 relation does not exist`.
 */
import { migrate } from 'drizzle-orm/node-postgres/migrator';

import { db, pool } from './connection.js';

/** First table of `drizzle/0000_init.sql`: its absence means the migration never applied. */
const SENTINEL_TABLE = 'market_catalog';

/** Migration records already stored in `drizzle.__drizzle_migrations` (0 when the table is absent). */
async function appliedCount(): Promise<number> {
  try {
    const { rows } = await pool.query('select count(*)::int as count from drizzle.__drizzle_migrations');
    return rows[0].count as number;
  } catch {
    return 0;
  }
}

/** Newest migration record (hash and timestamp), used to explain a skipped run. */
async function lastRecordedMigration(): Promise<string | null> {
  try {
    const { rows } = await pool.query(
      'select hash, created_at from drizzle.__drizzle_migrations order by created_at desc limit 1',
    );
    return rows.length === 0 ? null : `${rows[0].hash.slice(0, 12)}… (created_at=${rows[0].created_at})`;
  } catch {
    return null;
  }
}

/**
 * Checks the migrated schema is present in `public` (`to_regclass` returns NULL otherwise).
 * A database error counts as "not ready" so callers can answer 503 instead of crashing.
 */
export async function schemaReady(): Promise<boolean> {
  try {
    const { rows } = await pool.query('select to_regclass($1) as table_name', [`public.${SENTINEL_TABLE}`]);
    return rows[0].table_name !== null;
  } catch {
    return false;
  }
}

/**
 * Runs every migration not yet recorded, logs what actually happened and fails when the
 * schema is still missing afterwards.
 */
export async function runMigrations(): Promise<void> {
  const before = await appliedCount();
  await migrate(db, { migrationsFolder: './drizzle' });
  const applied = (await appliedCount()) - before;
  console.log(applied > 0 ? `Database migrations applied (${applied})` : 'Database migrations up to date');
  if (!(await schemaReady())) {
    const last = await lastRecordedMigration();
    throw new Error(
      `Sanity check failed: relation "public.${SENTINEL_TABLE}" does not exist` +
        (last
          ? ` although the migrations table holds ${last} — that record is not from this service, check DATABASE_URL`
          : ' — the migrations were not applied'),
    );
  }
}
