/**
 * Applies pending SQL migrations from `./drizzle` at startup (generated by `pnpm db:generate`).
 */
import { migrate } from 'drizzle-orm/node-postgres/migrator';

import { db } from './connection.js';

/**
 * Runs all migrations not yet recorded in the drizzle migrations table.
 */
export async function runMigrations(): Promise<void> {
  await migrate(db, { migrationsFolder: './drizzle' });
}
