name: "Build & Deploy to Preprod: economie"

on:
  push:
    branches:
      - develop
    paths:
      - "economie/**"

jobs:
  build:
    name: Build economie (preprod)
    uses: ./.github/workflows/_build-push.yaml
    with:
      service_name: economie
      context_path: economie
      dockerfile_path: economie/docker/Dockerfile
      image_name: harbor.dyingstar-game.space/dyingstar/economie
      image_tag: develop
      chart_name: service-economie
      trigger_preprod_deploy: true
    secrets:
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      KUBERNETES_REPO_TOKEN: ${{ secrets.KUBERNETES_REPO_TOKEN }}