name: "Build & Deploy to Preprod: keycloak"

on:
  push:
    branches:
      - develop
    paths:
      - "keycloak/**"

jobs:
  build:
    name: Build keycloak (preprod)
    uses: ./.github/workflows/_build-push.yaml
    with:
      service_name: keycloak
      context_path: keycloak
      dockerfile_path: keycloak/docker/Dockerfile
      image_name: harbor.dyingstar-game.space/dyingstar/keycloak
      image_tag: develop
      chart_name: keycloak
      trigger_preprod_deploy: true
    secrets:
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      KUBERNETES_REPO_TOKEN: ${{ secrets.KUBERNETES_REPO_TOKEN }}
