name: "PR Build Check: keycloak"

on:
  pull_request:
    paths:
      - "keycloak/**"

jobs:
  build:
    name: Build keycloak (PR check)
    uses: ./.github/workflows/_build-push.yaml
    with:
      service_name: keycloak
      context_path: keycloak
      dockerfile_path: keycloak/docker/Dockerfile
      image_name: local/keycloak
      image_tag: pr-check
      push: false
