name: "PR Build Check: economie"

on:
  pull_request:
    paths:
      - "economie/**"

jobs:
  build:
    name: Build economie (PR check)
    uses: ./.github/workflows/_build-push.yaml
    with:
      service_name: economie
      context_path: economie
      dockerfile_path: economie/docker/Dockerfile
      image_name: local/economie
      image_tag: pr-check
      push: false