name: "PR Build Check: inventory"

on:
  pull_request:
    paths:
      - "inventory/**"

jobs:
  build:
    name: Build inventory (PR check)
    uses: ./.github/workflows/_build-push.yaml
    with:
      service_name: inventory
      context_path: inventory
      dockerfile_path: inventory/docker/Dockerfile
      image_name: local/inventory
      image_tag: pr-check
      push: false
