name: "Build & Deploy to Preprod: resourcesDynamic"

on:
  push:
    branches:
      - develop
    paths:
      - "resourcesDynamic/**"

jobs:
  build:
    name: Build resourcesDynamic (preprod)
    uses: ./.github/workflows/_build-push.yaml
    with:
      service_name: resourcesdynamic
      context_path: resourcesDynamic
      dockerfile_path: resourcesDynamic/docker/Dockerfile
      image_name: harbor.dyingstar-game.space/dyingstar/resourcesdynamic
      image_tag: develop
      chart_name: service-resourcesdynamic
      trigger_preprod_deploy: true
    secrets:
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      KUBERNETES_REPO_TOKEN: ${{ secrets.KUBERNETES_REPO_TOKEN }}
