name: "Build & Deploy to Preprod: chatauth"

on:
  push:
    branches:
      - develop
    paths:
      - "chatauth/**"

jobs:
  build:
    name: Build chatauth (preprod)
    uses: ./.github/workflows/_build-push.yaml
    with:
      service_name: chatauth
      context_path: chatauth
      dockerfile_path: chatauth/docker/Dockerfile
      image_name: harbor.dyingstar-game.space/dyingstar/chatauth
      image_tag: develop
      chart_name: service-chatauth
      trigger_preprod_deploy: true
    secrets:
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      KUBERNETES_REPO_TOKEN: ${{ secrets.KUBERNETES_REPO_TOKEN }}
