name: "Build & Deploy to Preprod: inventory"

on:
  push:
    branches:
      - develop
    paths:
      - "inventory/**"

jobs:
  build:
    name: Build inventory (preprod)
    uses: ./.github/workflows/_build-push.yaml
    with:
      service_name: inventory
      context_path: inventory
      dockerfile_path: inventory/docker/Dockerfile
      image_name: harbor.dyingstar-game.space/dyingstar/inventory
      image_tag: develop
      chart_name: service-inventory
      trigger_preprod_deploy: true
    secrets:
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      KUBERNETES_REPO_TOKEN: ${{ secrets.KUBERNETES_REPO_TOKEN }}
